default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.05
    gamma: 0.99
    hidden_units: 256
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e7
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 3000
    use_recurrent: true
    use_curiosity: true
    curiosity_strength: 0.01
    curiosity_enc_size: 128